### ISSUE TITLE
Binder bot script needs to be fixed

### ISSUE THREAD

**Issue by MridulS** [gesiscss/orc#47]
Error log from the update-binder pod.

```
Cloning into 'orc_repo'...
WARNING: You are using pip version 19.3; however, version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2021-07-02 18:25:23,878 INFO {'binderhub': {'live': '0.2.0-n577.h14cc6c7', 'latest': '0.2.0-n604.h9bc978a'}, 'repo2docker': {'live': '2021.03.0-15.g73ab48a', 'latest': '2021.03.0-23.gea90ae2'}, 'jupyterhub': {'live': '0.11.1', 'latest': '1.0.1'}}
2021-07-02 18:25:23,878 INFO repo2docker:2021.03.0-15.g73ab48a-->2021.03.0-23.gea90ae2
Traceback (most recent call last):
File "orc_repo/gesisbinder/bot/bot.py", line 393, in <module>
b.update_repos(['repo2docker', 'binderhub'])
File "orc_repo/gesisbinder/bot/bot.py", line 254, in update_repos
self.set_gitlab_project_id(GL_REPO_NAME)
File "orc_repo/gesisbinder/bot/bot.py", line 75, in set_gitlab_project_id
if project['name'] == repo_name:
TypeError: string indices must be integers
```

Could be due to recent upgrades to gesis gitlab.

**Comment by MridulS** [comment]
The token stopped working after the recent GitLab upgrade. Created a new token and the bot is back up.
